extend-exclude = ["migrations"]

[lint]

exclude = ["test_*.py"]

select = [
    "D", # pydocstyle
]

ignore = [
    "D101", # Missing docstring in public class
    "D200", # One-line docstring should fit on one line
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
    "D215", # Section underline is over-indented
    "D404", # First word of the docstring should not be "This"
    "D405", # Section name should be properly capitalized
    "D406", # Section name should end with a newline
    "D407", # Missing dashed underline after section
    "D408", # Section underline should be in the line following the section's name
    "D409", # Section underline should match the length of its name
    "D410", # Missing blank line after section
    "D411", # Missing blank line before section
    "D412", # No blank lines allowed between a section header and its content
    "D413", # Missing blank line after last section
    "D414", # Section has no content
]
